### ISSUE TITLE
checked in git conflict markers

### ISSUE THREAD

**Issue by pabra** [majal/maj-server#2]
https://github.com/majal/maj-server/blob/efb88d22e79fd2f510559722f33c9472574eb4e9/nginx-modules-brotli/mkbrotli#L19-L23

**Comment by majal** [comment]
Thank you @pabra! Good catch. This has now been fixed by https://github.com/majal/maj-server/commit/8451c91f7165588f9d244f4d4e8c976e323b4cf1. Thank you for the heads up.
